### ISSUE TITLE
Make Releases

### ISSUE THREAD

**Issue by ijnek** [ros-sports/r2r_spl#25]
Make release for:
- [x] foxy - ros/rosdistro#34097
- [x] galactic - ros/rosdistro#34096
- [x] humble - ros/rosdistro#34095
- [x] rolling - ros/rosdistro#34094
